// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLsFgMQyw0DGVQaSru1faZq1mZ_7VBVpc',
    appId: '1:989278047275:web:189e27a3d50b220ed3ae6e',
    messagingSenderId: '989278047275',
    projectId: 'trogo-dcdf5',
    authDomain: 'trogo-dcdf5.firebaseapp.com',
    storageBucket: 'trogo-dcdf5.appspot.com',
    measurementId: 'G-MPCMR7KS52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtFUtvm7YSu6mk9ksv4q168MLlFvy_gWo',
    appId: '1:989278047275:android:8114c128031b67b3d3ae6e',
    messagingSenderId: '989278047275',
    projectId: 'trogo-dcdf5',
    storageBucket: 'trogo-dcdf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChar4yFbLe0COGaNVqpgDo1cP3KwCf53w',
    appId: '1:989278047275:ios:f4b082e54c488fa3d3ae6e',
    messagingSenderId: '989278047275',
    projectId: 'trogo-dcdf5',
    storageBucket: 'trogo-dcdf5.appspot.com',
    iosBundleId: 'com.example.trogoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChar4yFbLe0COGaNVqpgDo1cP3KwCf53w',
    appId: '1:989278047275:ios:f4b082e54c488fa3d3ae6e',
    messagingSenderId: '989278047275',
    projectId: 'trogo-dcdf5',
    storageBucket: 'trogo-dcdf5.appspot.com',
    iosBundleId: 'com.example.trogoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLsFgMQyw0DGVQaSru1faZq1mZ_7VBVpc',
    appId: '1:989278047275:web:9b54ddeaf33afa3ed3ae6e',
    messagingSenderId: '989278047275',
    projectId: 'trogo-dcdf5',
    authDomain: 'trogo-dcdf5.firebaseapp.com',
    storageBucket: 'trogo-dcdf5.appspot.com',
    measurementId: 'G-NZE497V75X',
  );
}
